#!/usr/bin/env python3
                                                                                                                                                                                                                                                                               
import requests
import json

token = '4naZcjTLwMO4cytfDxgSCosk75LaAty0Q3NfyqmZ'
host = 'c118bdec-44e1-4aef-8b79-9c58ba736871'
service = '9181b9fe-c92d-4096-a1b2-2a7803ca01cb'
value = 80


def store(token, hostUuid, serviceUuid, value):
    payload = {"service-id": serviceUuid, "value": value}

    url = 'https://dawimon.wiebekn.dev/api/store/' + hostUuid
    request_headers = { "Content-Type" : "application/json",
                        "Accept":"application/json",
                        "Authorization" : "Bearer " + token }
    response = requests.post(url,data=json.dumps(payload),headers=request_headers,verify=False)
    return response.json()


store(token, host, service, value)