#!/usr/bin/env python3
                                                                                                                                                                                                                                                                               
import requests
import json

with open('../config.json') as config_file:
    conf = json.load(config_file)

token = conf['token']
base_url = conf['base_url']
host_id = conf['host_id']

#print(conf)

if "develop" in conf:
    develop = conf['develop']
else:
    develop = False

blnVerify = (develop == False)

request_headers = { "Content-Type" : "application/json",
                    "Accept":"application/json",
                    "Authorization" : "Bearer " + token }

url = base_url + '/api/config/' + host_id

response = requests.get(url,headers=request_headers,verify=blnVerify)
json_data = json.loads(response.text)

print(json_data)

# services = json_data['data']['service'];

# for service in services:
#     print(service['id'])
#     print(service['path'])
#     print()
